name: Update Version Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Read Version from gradle.properties
        id: version
        run: echo "VERSION=$(grep '^version' gradle.properties | cut -d= -f2)" >> $GITHUB_ENV

      - name: Check for Changes
        id: git-check
        run: echo "CHANGES_DETECTED=true"

      - name: Commit and Push Changes
        if: steps.git-check.outputs.changes_detected == 'true'
        env:
          PAT_TOKEN: ${{ secrets.TRY }}
        run: |
          git add README.md
          git commit -m "Update version badge [skip ci]"
          git remote add origin_with_token https://${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin_with_token
