name: Update Version Badge

on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Display gradle.properties Content
      run: cat gradle.properties

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Read Version Number
      id: version
      run: |
        grep '^version' gradle.properties || echo "Version not found in gradle.properties"
        echo "VERSION=$(grep '^version' gradle.properties | cut -d= -f2)" >> $GITHUB_ENV
        echo "VERSION: ${{ steps.version.outputs.VERSION }}"

    - name: Update README Badge
      run: |
        sed -i 's/\(badge\/version-v[0-9.]*-blue\.svg\?style=flat\&logo=java\)/badge\/version-v${{ steps.version.outputs.VERSION }}-blue.svg?style=flat\&logo=java/' README.md
        cat README.md  # Print README content for debugging

    - name: Check if Changes Exist
      id: git-check
      run: |
        if [ -n "$(git diff --name-only)" ]; then
          echo "Changes detected"
          echo "::set-output name=changes_detected::true"
        else
          echo "No changes detected"
          echo "::set-output name=changes_detected::false"
        fi

    - name: Commit and Push Changes
      if: steps.git-check.outputs.changes_detected == 'true'
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add README.md
        git commit -m "Update version badge [skip ci]"
        git push
